apiVersion: v1
kind: Secret
metadata:
  name: cloudkart-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/part-of: cloudkart
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.jwt.secret | quote }}
